### ISSUE TITLE
What is this websites purpose?

### ISSUE THREAD

**Issue by ghost** [ScratchLink1/scratchlink.cf#1]
Jut to clarify, what is the purpose of this website. You can host through GitHub pages if you were looking for custom domains

**Comment by icarusinthewings** [comment]
I Know, the custom domain works now. I got it for free :)
The website is currently going to be the landing page.

**Comment by ghost** [comment]
there's a problem. it's scratchlink1 not scratchlink. I think we should stick to the original repo because that is hosting all current work...

**Comment by icarusinthewings** [comment]
kk
